module CommentsHelper
  def comment_input_field_options(field)
    options = {
      :label    => field.label,
      #:hint     => field.hint,
      :required => field.required?,
    }


    case field
    when RegulationsDotGov::CommentForm::Field::TextField
      # the regs.gov API returns a max-length of -1 to mean a textarea capped at 2000 characters
      if field.max_length >= 2000
        options.merge!(
          :as => :text,
          :wrapper_html => {
            :'data-max-size' => field.max_length,
            :'data-size-warn-at' => 250
          }
        )
      else
        options.merge!(
          :as => :string,
          :size => field.max_length,
          :wrapper_html => {
            :'data-max-size' => field.max_length,
            :'data-size-warn-at' => 7
          }
        )
      end
    when RegulationsDotGov::CommentForm::Field::SelectField
      options.merge!(
        :as => :select,
        :collection => field.option_values,
        :member_value => :value,
        :member_label => :label
      )
    when RegulationsDotGov::CommentForm::Field::ComboField
      options.merge!(
        :as => :string,
        :wrapper_html => {
          :class => "combo",
          :'data-dependent-on' => field.dependent_on,
          :'data-dependencies' => field.dependencies.to_json
        }
      )
    end

    if field.publically_viewable?
      options[:wrapper_html] ||= {}
      options[:wrapper_html][:class] = [options[:wrapper_html][:class], "public"].compact.join(' ')
    end

    options
  end

  def state_options
    [
      ['Alaska','AK'],
      ['Alabama','AL'],
      ['Arkansas','AR'],
      ['American Samoa','AS'],
      ['Arizona','AZ'],
      ['California','CA'],
      ['Colorado','CO'],
      ['Connecticut','CT'],
      ['District of Columbia','DC'],
      ['Delaware','DE'],
      ['Florida','FL'],
      ['Georgia','GA'],
      ['Guam','GU'],
      ['Hawaii','HI'],
      ['Iowa','IA'],
      ['Idaho','ID'],
      ['Illinois','IL'],
      ['Indiana','IN'],
      ['Kansas','KS'],
      ['Kentucky','KY'],
      ['Louisiana','LA'],
      ['Massachusetts','MA'],
      ['Maryland','MD'],
      ['Maine','ME'],
      ['Michigan','MI'],
      ['Minnesota','MN'],
      ['Missouri','MO'],
      ['Mississippi','MS'],
      ['Montana','MT'],
      ['North Carolina','NC'],
      ['North Dakota','ND'],
      ['Northern Mariana Islands','MP'],
      ['Nebraska','NE'],
      ['New Hampshire','NH'],
      ['New Jersey','NJ'],
      ['New Mexico','NM'],
      ['Nevada','NV'],
      ['New York','NY'],
      ['Ohio','OH'],
      ['Oklahoma','OK'],
      ['Oregon','OR'],
      ['Pennsylvania','PA'],
      ['Puerto Rico','PR'],
      ['Rhode Island','RI'],
      ['South Carolina','SC'],
      ['South Dakota','SD'],
      ['Tennessee','TN'],
      ['Texas','TX'],
      ['US Virgin Islands','VI'],
      ['Utah','UT'],
      ['Virginia','VA'],
      ['Vermont','VT'],
      ['Washington','WA'],
      ['Wisconsin','WI'],
      ['West Virginia','WV'],
      ['Wyoming','WY'],
    ]
  end

  def country_options
    [
      "Afghanistan",
      "Åland Islands",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia, Plurinational State of",
      "Bonaire, Sint Eustatius and Saba",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Congo",
      "Congo, the Democratic Republic of the",
      "Cook Islands",
      "Costa Rica",
      "Côte d'Ivoire",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Falkland Islands (Malvinas)",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Holy See (Vatican City State)",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran, Islamic Republic of",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea, Democratic People's Republic of",
      "Korea, Republic of",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao",
      "Macedonia, the Former Yugoslav Republic of",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia, Federated States of",
      "Moldova, Republic of",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine, State of",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Réunion",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Saint Barthélemy",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin (French part)",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten (Dutch part)",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Svalbard and Jan Mayen",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan, Province of China",
      "Tajikistan",
      "Tanzania, United Republic of",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "United States Minor Outlying Islands",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela, Bolivarian Republic of",
      "Viet Nam",
      "Virgin Islands, British",
      "Virgin Islands, U.S.",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ]
  end

end
