#!/bin/bash

# only worker container should run migrate and clear cache
if ! [ "$CONTAINER_ROLE" = "worker" ]; then
  rm -f /etc/my_init.d/migrate
  rm -f /etc/my_init.d/varnish
  rm -rf /etc/my_init.d/whenever
fi

### Development Environment
if ! [ "$RAILS_ENV" = "development" ]; then
  rm -rf /etc/my_init.d/bundle
fi
