#!/bin/bash
set -ex
cd /home/app
if [ "$RAILS_ENV" == "development" ]; then
  exec /sbin/setuser app bundle exec rake db:create:all db:migrate
else
  exec /sbin/setuser app bundle exec rake db:migrate
fi
